### ISSUE TITLE
Support review of other AWS Accounts

### ISSUE THREAD

**Issue by kellington** [awslabs/aws-security-assessment-solution#10]
We have multiple AWS Accounts - different environments/services.  It would be better if this utility could be run from 1 account and then review the security settings in multiple other accounts.

**Comment by aws-brad** [comment]
Hi there, because this would require the creation of a cross account trust policy, we dont have any plans to add this into the default template.  That said, you can deploy the stack as a Cloudformation Stack-set, however you would need to allow all of the child accounts to be able to read and pull from the source account (the bucket where you put all the files).

The following documentation has some information on using stacksets:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html
